const styles = {
    container: {
        maxWidth: 520,
        margin: '48px auto',
        padding: 28,
        background: 'linear-gradient(135deg, #f7e967 0%, #a7e9f7 100%)',
        borderRadius: 12,
        border: '4px solid #2e3192',
        boxShadow: '0 0 0 8px #fff, 0 8px 32px #2e3192',
        fontFamily: 'Courier New, Courier, monospace',
        color: '#2e3192',
        textShadow: '1px 1px 0 #fff, 2px 2px 0 #a7e9f7',
        position: 'relative',
    },
    heading: {
        fontSize: 32,
        fontWeight: 'bold',
        letterSpacing: 2,
        marginBottom: 18,
        textAlign: 'center',
        color: '#d4145a',
        textShadow: '2px 2px 0 #fff, 4px 4px 0 #f7e967',
        fontFamily: 'Impact, Charcoal, sans-serif',
    },
    form: {
        display: 'flex',
        gap: 4,
        marginBottom: 16,
        justifyContent: 'center',
    },
    input: {
        flex: 1,
        padding: '10px 16px',
        borderRadius: 6,
        border: '2px solid #d4145a',
        fontSize: 20,
        maxWidth: 160,
        fontFamily: 'Courier New, Courier, monospace',
        background: '#fff',
        color: '#2e3192',
        boxShadow: '2px 2px 0 #f7e967',
    },
    button: {
        padding: '10px 24px',
        borderRadius: 6,
        border: '2px solid #2e3192',
        background: 'linear-gradient(90deg, #d4145a 0%, #fbb03b 100%)',
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        cursor: 'pointer',
        fontFamily: 'Impact, Charcoal, sans-serif',
        boxShadow: '2px 2px 0 #fff',
        textShadow: '1px 1px 0 #2e3192',
        transition: 'background 0.2s',
    },
    main: {
        marginLeft: 160,
        position: 'relative',
        minHeight: '100vh',
        transition: 'margin-left 0.3s ease',
        display: 'flex',
        flexDirection: 'column',
        height: 'calc(100vh - 48px)', // fill container minus heading
    },
    table: {
        width: '100%',
        flex: 1,
        borderCollapse: 'collapse',
        marginTop: 16,
        background: '#fafafa',
        borderRadius: 8,
        overflow: 'auto',
        boxShadow: '0 2px 8px #2e3192',
        border: '2px solid #2e3192',
        height: '100%',
        display: 'block',
    },
    th: {
        background: 'linear-gradient(90deg, #a7e9f7 0%, #f7e967 100%)',
        padding: '10px 8px',
        textAlign: 'left',
        fontWeight: 600,
        borderBottom: '2px solid #2e3192',
        fontFamily: 'Impact, Charcoal, sans-serif',
        color: '#2e3192',
        fontSize: 18,
    },
    td: {
        padding: '10px 8px',
        borderBottom: '1px solid #eaeaea',
        fontFamily: 'Courier New, Courier, monospace',
        fontSize: 16,
        color: '#05074e',
    },
    removeBtn: {
        background: 'linear-gradient(90deg, #d4145a 0%, #fbb03b 100%)',
        color: '#fff',
        border: '2px solid #2e3192',
        fontFamily: 'Impact, Charcoal, sans-serif',
        boxShadow: '2px 2px 0 #fff',
        textShadow: '1px 1px 0 #2e3192',
        marginLeft: 0,
        padding: '8px 16px',
        borderRadius: 6,
        fontWeight: 'bold',
        fontSize: 16,
        cursor: 'pointer',
    },
};

export default styles;
